services:
  app:
    build: .
    container_name: manage_tg_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./sessions:/app/sessions
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 24101968h
      POSTGRES_DB: accounts_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: