"""update table view

Revision ID: 110b89f9b5e5
Revises: 448008ea62d5
Create Date: 2025-04-22 15:11:22.288701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110b89f9b5e5'
down_revision: Union[str, None] = '448008ea62d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view_actions', sa.Column('post_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view_actions', 'post_link')
    # ### end Alembic commands ###
