"""new migrate2

Revision ID: 1c7a7ac9e813
Revises: 7a6c6506b678
Create Date: 2025-04-14 11:06:09.820075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7a7ac9e813'
down_revision: Union[str, None] = '7a6c6506b678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('api_id', sa.Integer(), nullable=False))
    op.add_column('accounts', sa.Column('api_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'api_hash')
    op.drop_column('accounts', 'api_id')
    # ### end Alembic commands ###
