"""initial migration

Revision ID: 26725e02394c
Revises: 
Create Date: 2025-04-18 10:51:03.547129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26725e02394c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('positive_count', sa.Integer(), nullable=False))
    op.add_column('actions', sa.Column('negative_count', sa.Integer(), nullable=False))
    op.add_column('actions', sa.Column('critical_count', sa.Integer(), nullable=False))
    op.add_column('actions', sa.Column('question_count', sa.Integer(), nullable=False))
    op.add_column('actions', sa.Column('custom_prompt', sa.Text(), nullable=True))

    # Ensure the conversion of 'action_type' column to the ENUM type 'actiontype' is handled
    op.execute("ALTER TABLE actions ALTER COLUMN action_type TYPE actiontype USING action_type::actiontype")

    op.drop_column('actions', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))

    # Revert the conversion of 'action_type' column back to TEXT
    op.alter_column('actions', 'action_type',
                    existing_type=sa.Enum('comment', 'reaction', 'view', name='actiontype'),
                    type_=sa.TEXT(),
                    existing_nullable=False)

    op.drop_column('actions', 'custom_prompt')
    op.drop_column('actions', 'question_count')
    op.drop_column('actions', 'critical_count')
    op.drop_column('actions', 'negative_count')
    op.drop_column('actions', 'positive_count')
    # ### end Alembic commands ###