"""update table comment

Revision ID: 448008ea62d5
Revises: 6d3d935834b6
Create Date: 2025-04-22 14:43:55.258914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448008ea62d5'
down_revision: Union[str, None] = '6d3d935834b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_actions', sa.Column('neutral_count', sa.Integer(), nullable=False))
    op.drop_column('comment_actions', 'negative_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_actions', sa.Column('negative_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('comment_actions', 'neutral_count')
    # ### end Alembic commands ###
