"""Initial migration3

Revision ID: 6458036fed28
Revises: af4b22dcf5fc
Create Date: 2025-04-20 21:51:20.947270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6458036fed28'
down_revision: Union[str, None] = 'af4b22dcf5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_authorized', sa.Boolean(), nullable=False))
    op.drop_column('accounts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'is_authorized')
    # ### end Alembic commands ###
