"""update action table

Revision ID: 6d3d935834b6
Revises: 
Create Date: 2025-04-22 09:50:43.481094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3d935834b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_actions',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_time', sa.Integer(), nullable=False),
    sa.Column('random_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_actions_channel_id'), 'comment_actions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_comment_actions_id'), 'comment_actions', ['id'], unique=False)
    op.create_table('reaction_actions',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_time', sa.Integer(), nullable=False),
    sa.Column('random_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_actions_channel_id'), 'reaction_actions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_reaction_actions_id'), 'reaction_actions', ['id'], unique=False)
    op.create_table('view_actions',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_time', sa.Integer(), nullable=False),
    sa.Column('random_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_actions_channel_id'), 'view_actions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_view_actions_id'), 'view_actions', ['id'], unique=False)
    op.drop_index('ix_actions_channel_id', table_name='actions')
    op.drop_index('ix_actions_id', table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', postgresql.ENUM('comment', 'reaction', 'view', name='actiontype'), autoincrement=False, nullable=False),
    sa.Column('positive_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('negative_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('critical_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('random_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='actions_channel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='actions_pkey')
    )
    op.create_index('ix_actions_id', 'actions', ['id'], unique=False)
    op.create_index('ix_actions_channel_id', 'actions', ['channel_id'], unique=False)
    op.drop_index(op.f('ix_view_actions_id'), table_name='view_actions')
    op.drop_index(op.f('ix_view_actions_channel_id'), table_name='view_actions')
    op.drop_table('view_actions')
    op.drop_index(op.f('ix_reaction_actions_id'), table_name='reaction_actions')
    op.drop_index(op.f('ix_reaction_actions_channel_id'), table_name='reaction_actions')
    op.drop_table('reaction_actions')
    op.drop_index(op.f('ix_comment_actions_id'), table_name='comment_actions')
    op.drop_index(op.f('ix_comment_actions_channel_id'), table_name='comment_actions')
    op.drop_table('comment_actions')
    # ### end Alembic commands ###
