"""new migrate

Revision ID: 7a6c6506b678
Revises: 0b0cee5e9df8
Create Date: 2025-04-14 10:22:35.696862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6c6506b678'
down_revision: Union[str, None] = '0b0cee5e9df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_channels_account_id', table_name='channels')
    op.drop_constraint('channels_account_id_fkey', 'channels', type_='foreignkey')
    op.drop_column('channels', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('channels_account_id_fkey', 'channels', 'accounts', ['account_id'], ['id'])
    op.create_index('ix_channels_account_id', 'channels', ['account_id'], unique=False)
    # ### end Alembic commands ###
