"""new migrate

Revision ID: 966bb6beba49
Revises: 1c7a7ac9e813
Create Date: 2025-04-14 11:17:28.724720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966bb6beba49'
down_revision: Union[str, None] = '1c7a7ac9e813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'proxy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'proxy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
